name: Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
            version: 9.10.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Upload Docs
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: pages
          path: './docs'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: source
          path: './'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: pages

  publish:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
            version: 9.10.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'


      - name: Download build output
        uses: actions/download-artifact@v4.1.8
        with:
          name: source

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}